#
# This file is autogenerated by knowntypes_builder.py
#
# DO NOT EDIT!
#

KNOWN_TYPES = [

#***************** SUPPORTED DPFS ***************************

###################### 128 x 128 ##############################

#
# abeyerr_black
#
# By superelchi, thx sairon
# 2012-06-20
#
{'Type': ['abeyerr_black'], 'Status': 'supported', 'Credit': ['By superelchi, thx sairon'], 'Date': ['2012-06-20'], 'CRC': [[4202393500, 2081370330]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# abeyerr_black_2
#
# By superelchi, thx kroonen
# 2013-01-17
#
{'Type': ['abeyerr_black_2'], 'Status': 'supported', 'Credit': ['By superelchi, thx kroonen'], 'Date': ['2013-01-17'], 'Url': ['http://www.ebay.com/itm/280828187564'], 'CRC': [[2726181921, 1032129360]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'No', 'ContrastMenuSupport': 'No'},

#
# abeyerr_black_3
#
# By superelchi, thx joelbl
# 2013-02-10
#
{'Type': ['abeyerr_black_3'], 'Status': 'supported', 'Credit': ['By superelchi, thx joelbl'], 'Date': ['2013-02-10'], 'Url': ['http://www.ebay.com/itm/280828187564'], 'CRC': [[2726181921, 2610964441]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# acme_1
#
# Unknown ebay seller
# By superelchi, thx RedoX
# 2012-07-24
#
{'Type': ['acme_1'], 'Comment': ['Unknown ebay seller'], 'Status': 'supported', 'Credit': ['By superelchi, thx RedoX'], 'Date': ['2012-07-24'], 'CRC': [[2726181921, 3130997315]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# acme_2
#
# Unknown manufacturer
# By superelchi, thx ax206geek, norefall
# 2012-10-10
#
{'Type': ['acme_2'], 'Comment': ['Unknown manufacturer'], 'Status': 'supported', 'Credit': ['By superelchi, thx ax206geek, norefall'], 'Date': ['2012-10-10'], 'CRC': [[3992676317, 608883650]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'No', 'ContrastMenuSupport': 'No'},

#
# acme_3
#
# By superelchi, thx johni85
# 2013-07-08
#
{'Type': ['acme_3'], 'Status': 'supported', 'Credit': ['By superelchi, thx johni85'], 'Date': ['2013-07-08'], 'CRC': [[4202393500, 1505862832, 2, 0]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'No', 'ContrastMenuSupport': 'No'},

#
# acme_5
#
# By superelchi, thx binary
# 2013-09-12
#
{'Type': ['acme_5'], 'Status': 'supported', 'Credit': ['By superelchi, thx binary'], 'Date': ['2013-09-12'], 'CRC': [[1825083451, 616707654, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# acme_6
#
# By superelchi, thx pepe
# 2013-09-13
#
{'Type': ['acme_6'], 'Status': 'supported', 'Credit': ['By superelchi, thx pepe'], 'Date': ['2013-09-13'], 'CRC': [[187369777, 2842286875, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# acme_7
#
# By superelchi, thx gioagril
# 2013-11-11
#
{'Type': ['acme_7'], 'Status': 'supported', 'Credit': ['By superelchi, thx gioagril'], 'Date': ['2013-11-11'], 'CRC': [[3943643383, 436450420, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# acme_8
#
# By superelchi, thx victorclaessen
# 2015-01-06
#
{'Type': ['acme_8'], 'Status': 'supported', 'Credit': ['By superelchi, thx victorclaessen'], 'Date': ['2015-01-06'], 'CRC': [[741602581, 530453805, 1, 1]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# acme_9
#
# By superelchi, thx pkrich.
# 2015-04-08
#
{'Type': ['acme_9'], 'Status': 'supported', 'Credit': ['By superelchi, thx pkrich.'], 'Date': ['2015-04-08'], 'CRC': [[2019707014, 3446734372, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# agk_violet
#
#
{'Type': ['agk_violet'], 'Status': 'supported', 'CRC': [[3589264857, 1422689575]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'No', 'ContrastMenuSupport': 'No'},

#
# august_dp150a
#
# By superelchi
# 2013-02-12
#
{'Type': ['august_dp150a'], 'Status': 'supported', 'Credit': ['By superelchi'], 'Date': ['2013-02-12'], 'Url': ['http://www.amazon.de/dp/B001N96F3I/ref=pe_217221_31005211_dp_1'], 'CRC': [[640222753, 3948976512, 1, 1]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# august_dp150l
#
# By superelchi, thx leonjoeann
# 2015-01-25
#
{'Type': ['august_dp150l'], 'Status': 'supported', 'Credit': ['By superelchi, thx leonjoeann'], 'Date': ['2015-01-25'], 'CRC': [[3229008242, 4127089957, 1, 1]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# avlabs_avl969s
#
# By ax206geek
# 2012-06-17
#
{'Type': ['avlabs_avl969s'], 'Status': 'supported', 'Credit': ['By ax206geek'], 'Date': ['2012-06-17'], 'Url': ['http://www.avlabs.net'], 'CRC': [[741602581, 838517843]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# bresser
#
# By superelchi, thx gothbert
# 2014-09-12
#
{'Type': ['bresser'], 'Status': 'supported', 'Credit': ['By superelchi, thx gothbert'], 'Date': ['2014-09-12'], 'CRC': [[3943643383, 1919922362, 2, 0]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'No', 'ContrastMenuSupport': 'No'},

#
# carrefour_bfv151
#
# By superelchi, thx assas1
# 2012-11-02
#
{'Type': ['carrefour_bfv151'], 'Status': 'supported', 'Credit': ['By superelchi, thx assas1'], 'Date': ['2012-11-02'], 'Url': ['http://www.mjshk.com/products/Digital%20Photo%20Frame/page/DPF815A_Max.htm', 'http://www.prixing.fr/products/bfv151-1-5-pouce-cadre-photo-porte-cles-carrefour-3606605023771'], 'CRC': [[3189525217, 3498632343]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# clas_ohlson
#
# By superelchi, thx BufferFramed
# 2012-12-05
#
{'Type': ['clas_ohlson'], 'Status': 'supported', 'Credit': ['By superelchi, thx BufferFramed'], 'Date': ['2012-12-05'], 'Url': ['http://www.clasohlson.com/fi/Avaimenper%C3%A4,-jossa-digitaalinen-valokuvakehys/Pr383925000'], 'CRC': [[640222753, 4127089957]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# clas_ohlson_2
#
# By superelchi, thx josef
# 2013-10-01
#
{'Type': ['clas_ohlson_2'], 'Status': 'supported', 'Credit': ['By superelchi, thx josef'], 'Date': ['2013-10-01'], 'CRC': [[2834891419, 2508033262, 1, 1]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# coby_dp151_bw
#
# By superelchi, thx mrlinux
# 2012-07-24
#
{'Type': ['coby_dp151_bw'], 'Status': 'supported', 'Credit': ['By superelchi, thx mrlinux'], 'Date': ['2012-07-24'], 'Url': ['http://www.ebay.com/itm/280828187564'], 'CRC': [[287174071, 805928632]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# coby_dp151_bw_2
#
# By superelchi, thx Deamon666
# 2013-08-18
#
{'Type': ['coby_dp151_bw_2'], 'Status': 'supported', 'Credit': ['By superelchi, thx Deamon666'], 'Date': ['2013-08-18'], 'CRC': [[3589761504, 3573247145, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# coby_dp151_bw_3
#
# By superelchi, thx maria
# 2013-11-29
#
{'Type': ['coby_dp151_bw_3'], 'Status': 'supported', 'Credit': ['By superelchi, thx maria'], 'Date': ['2013-11-29'], 'CRC': [[3189525217, 3570090448, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# coby_dp151_white
#
# By superelchi, thx donashe
# 2012-05-14
#
{'Type': ['coby_dp151_white'], 'Status': 'supported', 'Credit': ['By superelchi, thx donashe'], 'Date': ['2012-05-14'], 'Url': ['http://www.frys.com/product/5439059'], 'CRC': [[3562395993, 464803725]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'No', 'ContrastMenuSupport': 'No'},

#
# delightdigi_3
#
# By superelchi, thx fling
# 2013-06-18
#
{'Type': ['delightdigi_3'], 'Status': 'supported', 'Credit': ['By superelchi, thx fling'], 'Date': ['2013-06-18'], 'CRC': [[3589264857, 3321933551, 1, 1]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# delightdigi_black
#
# From ebay seller delight-digi
# By superelchi, thx rotitude
# 2012-04-22
#
{'Type': ['delightdigi_black'], 'Comment': ['From ebay seller delight-digi'], 'Status': 'supported', 'Credit': ['By superelchi, thx rotitude'], 'Date': ['2012-04-22'], 'CRC': [[3718890135, 3664700611]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# dx27893
#
# Works with dx #27893 (white) & #27894 (blue)
# By superelchi
# 2012-07-28
#
{'Type': ['dx27893'], 'Comment': ['Works with dx #27893 (white) & #27894 (blue)'], 'Status': 'supported', 'Credit': ['By superelchi'], 'Date': ['2012-07-28'], 'Url': ['http://www.dealextreme.com/p/1-5-lcd-rechargeable-digital-usb-photo-frame-keychain-white-107-picture-memory-storage-27893', 'http://www.dealextreme.com/p/1-5-lcd-rechargeable-digital-usb-photo-frame-keychain-blue-107-picture-memory-storage-27894', 'http://dx.com/p/1-5-lcd-rechargeable-digital-usb-photo-frame-keychain-with-8m-memory-for-140-photos-silver-33624', 'http://www.amazon.de/Technaxx-Keypix-Digitaler-Fotorahmen-interner/dp/B0013SJV4O', 'http://www.7dayshop.com/7dayshop-pebble-digital-photo-frame-1-5-tft-keyring-version-silver-irresistible-price'], 'CRC': [[3589264857, 1297118871, 1, 1], [3589264857, 2760090716, 1, 1]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# dx27893_2
#
# Variation of dx27893
# By superelchi, thx RedoX
# 2012-07-24
#
{'Type': ['dx27893_2'], 'Comment': ['Variation of dx27893'], 'Status': 'supported', 'Credit': ['By superelchi, thx RedoX'], 'Date': ['2012-07-24'], 'Url': ['http://www.dealextreme.com/p/1-5-lcd-rechargeable-digital-usb-photo-frame-keychain-white-107-picture-memory-storage-27893'], 'CRC': [[1743538178, 2452384647]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# eachdesk_tumbler
#
# Nice enclosure: tumbler design.
# By superelchi (thx c.dent)
# 2012-07-28
#
{'Type': ['eachdesk_tumbler'], 'Comment': ['Nice enclosure: tumbler design.'], 'Status': 'supported', 'Credit': ['By superelchi (thx c.dent)'], 'Date': ['2012-07-28'], 'Url': ['http://www.ebay.com/itm/Hot-1-5-Digital-Photo-Frame-Picture-Album-16MB-New-Tumbler-03-/110842497224'], 'CRC': [[3589264857, 1730849026]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# estation100
#
# By superelchi, thx galvan
# 2013-06-19
#
{'Type': ['estation100'], 'Status': 'supported', 'Credit': ['By superelchi, thx galvan'], 'Date': ['2013-06-19'], 'Url': ['http://www.ebay.com/itm/380532649879'], 'CRC': [[1797375145, 652807694, 1, 1]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# intertronic
#
# By superelchi, thx grouproot
# 2012-10-22
#
{'Type': ['intertronic'], 'Status': 'supported', 'Credit': ['By superelchi, thx grouproot'], 'Date': ['2012-10-22'], 'Url': ['http://www.interdiscount.ch/idshop/product/Spielwaren/873152_ER-324609050132160/INTERTRONIC_Digitaler_Bilderrahmen/detail.jsf'], 'CRC': [[3718890135, 1505088704]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# jovisa
#
# By superelchi, thx djJack
# 2012-09-19
#
{'Type': ['jovisa'], 'Status': 'supported', 'Credit': ['By superelchi, thx djJack'], 'Date': ['2012-09-19'], 'Url': ['http://www.jovisa.biz/images/egg%20dpf%20or%20copy.jpg'], 'CRC': [[2726181921, 2701100526]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# kaiser_baas_n1879
#
# From OfficeWorks (Perth Australia)
# By superelchi, thx John
# 2013-07-21
#
{'Type': ['kaiser_baas_n1879'], 'Comment': ['From OfficeWorks (Perth Australia) '], 'Status': 'supported', 'Credit': ['By superelchi, thx John'], 'Date': ['2013-07-21'], 'CRC': [[3589264857, 4097396536, 1, 1]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# kgmedia_m16
#
# By superelchi, thx Szymon
# 2014-04-16
#
{'Type': ['kgmedia_m16'], 'Status': 'supported', 'Credit': ['By superelchi, thx Szymon'], 'Date': ['2014-04-16'], 'Url': ['http://allegro.pl/show_item.php?item=4109505022'], 'CRC': [[640222753, 1987707687, 1, 1]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# lehoff
#
# Manufacturer unknow. Importer: Lehoff Im- und Export GmbH, Norderstedt
# By superelchi, thx gothbert
# 2014-09-12
#
{'Type': ['lehoff'], 'Comment': ['Manufacturer unknow. Importer: Lehoff Im- und Export GmbH, Norderstedt'], 'Status': 'supported', 'Credit': ['By superelchi, thx gothbert'], 'Date': ['2014-09-12'], 'CRC': [[569428222, 848704188, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# neckermann
#
# Gift from german seller neckermann.de (no longer available.)
# By superelchi, thx Anaeijon
# 2013-06-27
#
{'Type': ['neckermann'], 'Comment': ['Gift from german seller neckermann.de (no longer available.)'], 'Status': 'supported', 'Credit': ['By superelchi, thx Anaeijon '], 'Date': ['2013-06-27'], 'CRC': [[1825083451, 856513154, 2, 0]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'No', 'ContrastMenuSupport': 'No'},

#
# promedia
#
# By superelchi, thx kurczaczek
# 2014-03-28
#
{'Type': ['promedia'], 'Status': 'supported', 'Credit': ['By superelchi, thx kurczaczek'], 'Date': ['2014-03-28'], 'CRC': [[1905744767, 3248014671, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# ramka_m16
#
# "Menu-Off" does not work.
# By superelchi, thx firefox
# 2014-07-22
#
{'Type': ['ramka_m16'], 'Comment': ['"Menu-Off" does not work.'], 'Status': 'supported', 'Credit': ['By superelchi, thx firefox'], 'Date': ['2014-07-22'], 'CRC': [[2726181921, 3737892575, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# sevendayshop_pebble
#
# By superelchi, thx daveg
# 2012-10-19
#
{'Type': ['sevendayshop_pebble'], 'Status': 'supported', 'Credit': ['By superelchi, thx daveg'], 'Date': ['2012-10-19'], 'Url': ['http://www.7dayshop.com/7dayshop-pebble-digital-photo-frame-1-5-tft-keyring-version-silver-irresistible-price'], 'CRC': [[1493111108, 2479827774]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'No', 'ContrastMenuSupport': 'No'},

#
# sunluxy
#
# By superelchi, thx glb
# 2013-01-27
#
{'Type': ['sunluxy'], 'Status': 'supported', 'Credit': ['By superelchi, thx glb'], 'Date': ['2013-01-27'], 'Url': ['http://www.amazon.fr/gp/product/B00AQV277C/'], 'CRC': [[2726181921, 3709981863]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# sweex_mm004v5_2
#
# By superelchi, thx free8bee
# 2014-12-25
#
{'Type': ['sweex_mm004v5_2'], 'Status': 'supported', 'Credit': ['By superelchi, thx free8bee'], 'Date': ['2014-12-25'], 'CRC': [[3189525217, 584147790, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# sweex_mv004v4
#
# By superelchi, thx jon2099
# 2015-02-26
#
{'Type': ['sweex_mv004v4'], 'Status': 'supported', 'Credit': ['By superelchi, thx jon2099'], 'Date': ['2015-02-26'], 'CRC': [[3589264857, 4268180508, 1, 1]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# sweex_mv004v5
#
# By superelchi, thx Magnetohh
# 2014-02-27
#
{'Type': ['sweex_mv004v5'], 'Status': 'supported', 'Credit': ['By superelchi, thx Magnetohh'], 'Date': ['2014-02-27'], 'CRC': [[500235953, 2477824216, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# tao_80013
#
# By superelchi, thx richard
# 2013-07-21
#
{'Type': ['tao_80013'], 'Status': 'supported', 'Credit': ['By superelchi, thx richard'], 'Date': ['2013-07-21'], 'Url': ['http://cpc.farnell.com/jsp/search/productdetail.jsp?sku=CS1967434'], 'CRC': [[640222753, 4280902475, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# veovision
#
# By superelchi, thx ternyk
# 2013-02-13
#
{'Type': ['veovision'], 'Status': 'supported', 'Credit': ['By superelchi, thx ternyk'], 'Date': ['2013-02-13'], 'CRC': [[3589264857, 3308761215]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# vivitar
#
# By superelchi, thx metallurge and parkerlreed for his help to get the buttons working
# 2015-07-05
#
{'Type': ['vivitar'], 'Status': 'supported', 'Credit': ['By superelchi, thx metallurge and parkerlreed for his help to get the buttons working'], 'Date': ['2015-07-05'], 'CRC': [[640222753, 756959522, 2, 0]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'No', 'ContrastMenuSupport': 'No'},

#
# weltild
#
# By superelchi, thx leonjoeann
# 2014-07-30
#
{'Type': ['weltild'], 'Status': 'supported', 'Credit': ['By superelchi, thx leonjoeann'], 'Date': ['2014-07-30'], 'CRC': [[2469228728, 400340726, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# wh_smith
#
# By superelchi, thx free8bee
# 2014-12-25
#
{'Type': ['wh_smith'], 'Status': 'supported', 'Credit': ['By superelchi, thx free8bee'], 'Date': ['2014-12-25'], 'CRC': [[2280663442, 3485091384, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# xg4241
#
# Does not use standard LcdInit. Direct lcd access (NOT using otp_lcd_write).
# By superelchi (thx marcusbrutus)
# 2013-03-17
#
{'Type': ['xg4241'], 'Comment': ['Does not use standard LcdInit. Direct lcd access (NOT using otp_lcd_write).'], 'Status': 'supported', 'Credit': ['By superelchi (thx marcusbrutus)'], 'Date': ['2013-03-17'], 'Url': ['http://dicksmith.com.au/product/XG4241/dick-smith-1-5-quot-digital-photo-frame-keyring'], 'CRC': [[2280663442, 4014062118, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# xp1000
#
# By superelchi (thx nonzhe)
# 2014-05-05
#
{'Type': ['xp1000'], 'Status': 'supported', 'Credit': ['By superelchi (thx nonzhe)'], 'Date': ['2014-05-05'], 'CRC': [[1905744767, 4106581639, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# xp1000_2
#
# By superelchi
# 2014-05-15
#
{'Type': ['xp1000_2'], 'Status': 'supported', 'Credit': ['By superelchi'], 'Date': ['2014-05-15'], 'CRC': [[2726181921, 2701946263, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# zipp_dp605
#
# Sold in Australia by Big W / Woolworths.
# By superelchi (thx CaptainCheeks)
# 2013-03-05
#
{'Type': ['zipp_dp605'], 'Comment': ['Sold in Australia by Big W / Woolworths.'], 'Status': 'supported', 'Credit': ['By superelchi (thx CaptainCheeks)'], 'Date': ['2013-03-05'], 'CRC': [[3589761504, 605483227, 2, 2]], 'Lcd_width': '128', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

###################### 128 x 144 ##############################

#
# focalprice144
#
# By superelchi
#
{'Type': ['focalprice144'], 'Status': 'supported', 'Credit': ['By superelchi'], 'CRC': [[811528212, 1201222071]], 'Lcd_width': '128', 'Lcd_height': '144', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

###################### 130 x 130 ##############################

#
# zipp_dp605_2
#
# Orginal firmware reports 132x132 pixel, viewable area is 130x130 pixel.
# By superelchi, thx ajd4096
# 2014-07-21
#
{'Type': ['zipp_dp605_2'], 'Comment': ['Orginal firmware reports 132x132 pixel, viewable area is 130x130 pixel.'], 'Status': 'supported', 'Credit': ['By superelchi, thx ajd4096'], 'Date': ['2014-07-21'], 'CRC': [[2251776829, 2972503213, 2, 2]], 'Lcd_width': '130', 'Lcd_height': '130', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

###################### 160 x 128 ##############################

#
# coby_dp180
#
# By superelchi (thx johni)
# 2013-03-02
#
{'Type': ['coby_dp180'], 'Status': 'supported', 'Credit': ['By superelchi (thx johni)'], 'Date': ['2013-03-02'], 'Url': ['http://www.cobyusa.com/?p=prod&prod_num_id=411&pcat_id=4001'], 'CRC': [[553029627, 623803278, 2, 2]], 'Lcd_width': '160', 'Lcd_height': '128', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

###################### 240 x 320 ##############################

#
# delightdigi_2_portrait
#
# Portrait mode, different enclosure, battery powered
# By superelchi, thx dms
# 2012-09-28
#
{'Type': ['delightdigi_2_portrait'], 'Comment': ['Portrait mode, different enclosure, battery powered'], 'Status': 'supported', 'Credit': ['By superelchi, thx dms'], 'Date': ['2012-09-28'], 'Url': ['http://www.ebay.com/itm/280736717264'], 'CRC': [[472729229, 1980929741, 1, 1]], 'Lcd_width': '240', 'Lcd_height': '320', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# fanray
#
# From Alibaba - Fanray Type FR-024SA-8 (AM)
# By superelchi, thx maxipes
# 2015-11-16
#
{'Type': ['fanray'], 'Comment': ['From Alibaba - Fanray Type FR-024SA-8 (AM)'], 'Status': 'supported', 'Credit': ['By superelchi, thx maxipes'], 'Date': ['2015-11-16'], 'Url': ['http://www.alibaba.com/product-detail/2-4-inch-TFT-nice-gift_506523246.html?spm=a2700.7724857.29.46.QLp7IF'], 'CRC': [[1345150332, 3304277511, 2, 1]], 'Lcd_width': '240', 'Lcd_height': '320', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# linkdelight_black_portrait
#
# Portrait mode, different enclosure, battery powered
# By superelchi, thx Papa Oscar
# 2013-01-18
#
{'Type': ['linkdelight_black_portrait'], 'Comment': ['Portrait mode, different enclosure, battery powered'], 'Status': 'supported', 'Credit': ['By superelchi, thx Papa Oscar'], 'Date': ['2013-01-18'], 'Url': [' http://www.ebay.com/itm/230670117410'], 'CRC': [[3230522243, 2026185173, 1, 1]], 'Lcd_width': '240', 'Lcd_height': '320', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# linkdelight_black_portrait_2
#
# Variation of linkdelight_black_portrait
# By superelchi (thx Mr. P)
# 2013-03-27
#
{'Type': ['linkdelight_black_portrait_2'], 'Comment': ['Variation of linkdelight_black_portrait'], 'Status': 'supported', 'Credit': ['By superelchi (thx Mr. P)'], 'Date': ['2013-03-27'], 'CRC': [[1040606659, 902033657, 1, 1]], 'Lcd_width': '240', 'Lcd_height': '320', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# linkdelight_black_portrait_3
#
# Another variation of linkdelight_black_portrait
# By superelchi, thx prezes551
# 2013-05-09
#
{'Type': ['linkdelight_black_portrait_3'], 'Comment': ['Another variation of linkdelight_black_portrait'], 'Status': 'supported', 'Credit': ['By superelchi, thx prezes551'], 'Date': ['2013-05-09'], 'Url': ['http://www.ebay.com/itm/230670117410'], 'CRC': [[1040606659, 2896831531, 1, 1]], 'Lcd_width': '240', 'Lcd_height': '320', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# pt824_2
#
# By suoperelchi (thx nonzhe)
# 2014-01-28
#
{'Type': ['pt824_2'], 'Status': 'supported', 'Credit': ['By suoperelchi (thx nonzhe)'], 'Date': ['2014-01-28'], 'CRC': [[472729229, 522068028, 1, 1]], 'Lcd_width': '240', 'Lcd_height': '320', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# yallstock_black_portrait
#
# By superelchi (thx dkrusko)
#
{'Type': ['yallstock_black_portrait'], 'Status': 'supported', 'Credit': ['By superelchi (thx dkrusko)'], 'Url': ['http://www.ebay.com/itm/400391394538'], 'CRC': [[4077944897, 334688753, 1, 1]], 'Lcd_width': '240', 'Lcd_height': '320', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# yallstock_black_portrait_2
#
# By superelchi (thx oberseeler)
# 2014-01-26
#
{'Type': ['yallstock_black_portrait_2'], 'Status': 'supported', 'Credit': ['By superelchi (thx oberseeler)'], 'Date': ['2014-01-26'], 'Url': ['http://www.ebay.com/itm/400391394538?ssPageName=STRK:MEWNX:IT'], 'CRC': [[492873149, 1368737794, 1, 1]], 'Lcd_width': '240', 'Lcd_height': '320', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

###################### 320 x 240 ##############################

#
# acme_4
#
# unknown ebay seller.
# By superelchi, thx nexus
# 2013-09-05
#
{'Type': ['acme_4'], 'Comment': ['unknown ebay seller.'], 'Status': 'supported', 'Credit': ['By superelchi, thx nexus'], 'Date': ['2013-09-05'], 'CRC': [[817616278, 404446180, 1, 1]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# dhgate
#
# 50 pieces/lot
# By superelchi, thx Rollkopf
# 2013-08-16
#
{'Type': ['dhgate'], 'Comment': ['50 pieces/lot'], 'Status': 'supported', 'Credit': ['By superelchi, thx Rollkopf'], 'Date': ['2013-08-16'], 'Url': ['http://www.dhgate.com/product/2-4-inch-multifunctional-lcd-digital-photo/143997976.html'], 'CRC': [[1317613437, 855243777, 1, 1]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# dinodirect
#
# By superelchi, thx kodi
# 2013-05-31
#
{'Type': ['dinodirect'], 'Status': 'supported', 'Credit': ['By superelchi, thx kodi'], 'Date': ['2013-05-31'], 'Url': ['http://www.dinodirect.com/2-4-LCD-16MB-Digital-Photo-Frame-White.html'], 'CRC': [[390860985, 2045744741, 2, 1]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# dx104500
#
# By superelchi
#
{'Type': ['dx104500'], 'Status': 'supported', 'Credit': ['By superelchi'], 'Url': ['http://www.dealextreme.com/p/stylish-a33-2-4-lcd-desktop-digital-photo-picture-frame-album-silver-16mb-104500'], 'CRC': [[3029278881, 3683529480, 2, 0]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'No', 'ContrastMenuSupport': 'No'},

#
# dx104838
#
# No Brightness control. Only on/off supported.
# By superelchi
#
{'Type': ['dx104838'], 'Comment': ['No Brightness control. Only on/off supported.'], 'Status': 'supported', 'Credit': ['By superelchi'], 'Url': ['http://www.dealextreme.com/p/stylish-a18-2-4-lcd-desktop-digital-photo-picture-frame-album-white-silver-16mb-104838'], 'CRC': [[3790308462, 2319538268, 0, 0]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'No', 'ContrastMenuSupport': 'No'},

#
# dx104838_2
#
# No Brightness control. Only on/off supported.
# By superelchi (thx j3r, mihre)
#
{'Type': ['dx104838_2'], 'Comment': ['No Brightness control. Only on/off supported.'], 'Status': 'supported', 'Credit': ['By superelchi (thx j3r, mihre)'], 'Url': ['http://www.dealextreme.com/p/stylish-a18-2-4-lcd-desktop-digital-photo-picture-frame-album-white-silver-16mb-104838'], 'CRC': [[3029278881, 3683529480, 0, 0]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'No', 'ContrastMenuSupport': 'No'},

#
# dx104838_3
#
# No Brightness control. Only on/off supported.
# By superelchi (thx ralf001)
#
{'Type': ['dx104838_3'], 'Comment': ['No Brightness control. Only on/off supported.'], 'Status': 'supported', 'Credit': ['By superelchi (thx ralf001)'], 'Url': ['http://www.dealextreme.com/p/stylish-a18-2-4-lcd-desktop-digital-photo-picture-frame-album-white-silver-16mb-104838'], 'CRC': [[3790308462, 4249249994, 0, 0]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'No', 'ContrastMenuSupport': 'No'},

#
# dx21334a
#
# By superelchi
#
{'Type': ['dx21334a'], 'Status': 'supported', 'Credit': ['By superelchi'], 'Url': ['http://www.dealextreme.com/p/2-4-lcd-desktop-digital-photo-frame-and-calendar-27-picture-memory-storage-21334'], 'CRC': [[3887821308, 1405237147, 1, 1]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# dx21334b
#
# By superelchi
#
{'Type': ['dx21334b'], 'Status': 'supported', 'Credit': ['By superelchi'], 'Url': ['http://www.dealextreme.com/p/2-4-lcd-desktop-digital-photo-frame-and-calendar-27-picture-memory-storage-21334', 'http://www.ebay.de/itm/160792780280'], 'CRC': [[4101150613, 3339371474]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# focal_custom
#
# Replaces deprecated type focal
# By superelchi, thx mihre
# 2013-05-13
#
{'Type': ['focal_custom'], 'Comment': ['Replaces deprecated type focal'], 'Status': 'supported', 'Credit': ['By superelchi, thx mihre'], 'Date': ['2013-05-13'], 'CRC': [[390860985, 4226618260, 2, 1]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# focal_custom_2
#
# Replaces deprecated type focal
# By superelchi
# 2013-05-13
#
{'Type': ['focal_custom_2'], 'Comment': ['Replaces deprecated type focal'], 'Status': 'supported', 'Credit': ['By superelchi'], 'Date': ['2013-05-13'], 'CRC': [[390860985, 2754887347, 1, 1]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# keenox
#
# By superelchi (thx nexus)
# 2014-02-07
#
{'Type': ['keenox'], 'Status': 'supported', 'Credit': ['By superelchi (thx nexus)'], 'Date': ['2014-02-07'], 'CRC': [[3029278881, 1724555793, 1, 2]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# keenox_1026
#
# No reset button
# By superelchi (thx BmD_Online)
# 2014-01-08
#
{'Type': ['keenox_1026'], 'Comment': ['No reset button'], 'Status': 'supported', 'Credit': ['By superelchi (thx BmD_Online)'], 'Date': ['2014-01-08'], 'CRC': [[3935538804, 10907679, 1, 1]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# kodak_g240
#
# By suoerelchi, thx Michael
# 2014-01-18
#
{'Type': ['kodak_g240'], 'Status': 'supported', 'Credit': ['By suoerelchi, thx Michael'], 'Date': ['2014-01-18'], 'CRC': [[1269253479, 3716381473, 2, 1]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'Yes'},

#
# linkdelight
#
# By superelchi
#
{'Type': ['linkdelight'], 'Status': 'supported', 'Credit': ['By superelchi'], 'Url': ['http://www.ebay.de/itm/ws/eBayISAPI.dll?ViewItem&rd=1&item=260978964426&ssPageName=STRK:MEAFB:IT', 'http://www.ebay.de/itm/New-Mini-2-4-inch-Digital-Time-Day-Calendar-Alarm-Clock-Photo-Frame-POF16-/260883908884?pt=LH_DefaultDomain_0&hash=item3cbde48914#ht_4709wt_1046'], 'CRC': [[860617845, 806655299, 1, 1]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# linkdelight_2
#
# Variation of linkdelight
# By superelchi, thx fred_feuerstein
# 2012-09-07
#
{'Type': ['linkdelight_2'], 'Comment': ['Variation of linkdelight'], 'Status': 'supported', 'Credit': ['By superelchi, thx fred_feuerstein'], 'Date': ['2012-09-07'], 'Url': ['http://www.ebay.de/itm/ws/eBayISAPI.dll?ViewItem&rd=1&item=260883908884'], 'CRC': [[841589230, 1030004459, 1, 1]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# linkdelight_3
#
# Variation of linkdelight
# By superelchi, thx ax206geek, m_K_o
# 2012-10-16
#
{'Type': ['linkdelight_3'], 'Comment': ['Variation of linkdelight'], 'Status': 'supported', 'Credit': ['By superelchi, thx ax206geek, m_K_o'], 'Date': ['2012-10-16'], 'Url': ['http://www.ebay.de/itm/260978964426?ssPageName=STRK:MEWNX:IT&_trksid=p3984.m1439.l2649'], 'CRC': [[3935538804, 3754832255]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# linkdelight_4
#
# Another variation of linkdelight
# By superelchi, thx Solo0815
# 2012-12-01
#
{'Type': ['linkdelight_4'], 'Comment': ['Another variation of linkdelight'], 'Status': 'supported', 'Credit': ['By superelchi, thx Solo0815'], 'Date': ['2012-12-01'], 'Url': ['http://www.ebay.de/itm/260978964426?ssPageName=STRK:MEWNX:IT&_trksid=p3984.m1497.l2649'], 'CRC': [[1722727966, 3339371474]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# linkdelight_5
#
# Another variation of linkdelight
# By superelchi
#
{'Type': ['linkdelight_5'], 'Comment': ['Another variation of linkdelight'], 'Status': 'supported', 'Credit': ['By superelchi'], 'Url': ['http://www.ebay.de/itm/ws/eBayISAPI.dll?ViewItem&item=110897096126'], 'CRC': [[2108676850, 2938400978]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# newfrog
#
# No Brightness control. Only on/off supported.
# By superelchi, thx LUISE
# 2013-06-24
#
{'Type': ['newfrog'], 'Comment': ['No Brightness control. Only on/off supported.'], 'Status': 'supported', 'Credit': ['By superelchi, thx LUISE'], 'Date': ['2013-06-24'], 'Url': ['http://www.newfrog.com/p/2-4-inch-usb-digital-time-day-calendar-alarm-clock-photo-frame-viewer-pof16-new-25642.html'], 'CRC': [[2532357239, 2963443671, 0, 0]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'No', 'ContrastMenuSupport': 'No'},

#
# pearl_custom
#
# Custom (flash-dump based) version of pearl
# By superelchi
# 2012-07-28
#
{'Type': ['pearl_custom'], 'Comment': ['Custom (flash-dump based) version of pearl'], 'Status': 'supported', 'Credit': ['By superelchi'], 'Date': ['2012-07-28'], 'Url': ['http://www.pearl.de/a-HPM1184-5618.shtml'], 'CRC': [[497821697, 3130612463, 2, 1]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# pt824
#
# Should work with PT824A/B/C.
# By superelchi (thx olderzeus)
# 2012-11-24
#
{'Type': ['pt824'], 'Comment': ['Should work with PT824A/B/C.'], 'Status': 'supported', 'Credit': ['By superelchi (thx olderzeus)'], 'Date': ['2012-11-24'], 'Url': ['http://item.taobao.com/item.htm?id=9197767508', 'http://www.longmatech.com/index.php/product/PT824A.html', 'http://www.longmatech.com/index.php/product/PT824A.html', 'http://lucy89.en.made-in-china.com/product/RbUxXeCrhvcJ/China-Christmas-Gifts-Digital-Photo-Frame-PT824b.html', 'http://konsun.appliances-china.com/Product_Look.php?ID=100077', 'http://www.corpmarket.com/sell/2-4inch-digital-photo-frame-PT824C-detail-1245-747967.html', 'http://www.gongchang.com/2_4_inch_color_LCD_display_PT824C_digital_picture_viewer_heart_shaped-dp621446/'], 'CRC': [[497821697, 3923636230]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# taobao
#
# Also used by linkdelight.
# By superelchi (thx cuckoohello)
# 2013-01-05
#
{'Type': ['taobao'], 'Comment': ['Also used by linkdelight.'], 'Status': 'supported', 'Credit': ['By superelchi (thx cuckoohello)'], 'Date': ['2013-01-05'], 'Url': ['http://item.taobao.com/item.htm?id=10380777914'], 'CRC': [[2212265512, 1765720342]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# taobao_2
#
# By superelchi, thx elickson
# 2013-09-24
#
{'Type': ['taobao_2'], 'Status': 'supported', 'Credit': ['By superelchi, thx elickson'], 'Date': ['2013-09-24'], 'Url': ['http://item.taobao.com/item.htm?id=5827115943'], 'CRC': [[1722727966, 3336180541, 1, 1]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

#
# winplus
#
# By superelchi, thx spooky2012
# 2014-05-07
#
{'Type': ['winplus'], 'Status': 'supported', 'Credit': ['By superelchi, thx spooky2012'], 'Date': ['2014-05-07'], 'CRC': [[1317613437, 1070586642, 1, 1]], 'Lcd_width': '320', 'Lcd_height': '240', 'ContrastSupport': 'Yes', 'ContrastMenuSupport': 'No'},

]
