#
# This file is autogenerated by knowntypes_builder.py
#
# DO NOT EDIT!
#

KNOWN_TYPES = [

#***************** SUPPORTED DPFS ***************************

###################### 128 x 128 ##############################

#
# abeyerr_black
#
# By superelchi, thx sairon
# 2012-06-20
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[4202393500, 2081370330]], 'Credit': ['By superelchi, thx sairon'], 'Lcd_height': '128', 'Date': ['2012-06-20'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['abeyerr_black']},

#
# abeyerr_black_2
#
# By superelchi, thx kroonen
# 2013-01-17
#
{'Status': 'supported', 'ContrastSupport': 'No', 'CRC': [[2726181921, 1032129360]], 'Url': ['http://www.ebay.com/itm/280828187564'], 'Credit': ['By superelchi, thx kroonen'], 'Lcd_height': '128', 'Date': ['2013-01-17'], 'Lcd_width': '128', 'ContrastMenuSupport': 'No', 'Type': ['abeyerr_black_2']},

#
# abeyerr_black_3
#
# By superelchi, thx joelbl
# 2013-02-10
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[2726181921, 2610964441]], 'Url': ['http://www.ebay.com/itm/280828187564'], 'Credit': ['By superelchi, thx joelbl'], 'Lcd_height': '128', 'Date': ['2013-02-10'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['abeyerr_black_3']},

#
# acme_1
#
# Unknown ebay seller
# By superelchi, thx RedoX
# 2012-07-24
#
{'Comment': ['Unknown ebay seller'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'Credit': ['By superelchi, thx RedoX'], 'CRC': [[2726181921, 3130997315]], 'Lcd_height': '128', 'Date': ['2012-07-24'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['acme_1']},

#
# acme_2
#
# Unknown manufacturer
# By superelchi, thx ax206geek, norefall
# 2012-10-10
#
{'Comment': ['Unknown manufacturer'], 'Status': 'supported', 'ContrastSupport': 'No', 'Credit': ['By superelchi, thx ax206geek, norefall'], 'CRC': [[3992676317, 608883650]], 'Lcd_height': '128', 'Date': ['2012-10-10'], 'Lcd_width': '128', 'ContrastMenuSupport': 'No', 'Type': ['acme_2']},

#
# acme_3
#
# By superelchi, thx johni85
# 2013-07-08
#
{'Status': 'supported', 'ContrastSupport': 'No', 'CRC': [[4202393500, 1505862832, 2, 0]], 'Credit': ['By superelchi, thx johni85'], 'Lcd_height': '128', 'Date': ['2013-07-08'], 'Lcd_width': '128', 'ContrastMenuSupport': 'No', 'Type': ['acme_3']},

#
# acme_5
#
# By superelchi, thx binary
# 2013-09-12
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[1825083451, 616707654, 2, 2]], 'Credit': ['By superelchi, thx binary'], 'Lcd_height': '128', 'Date': ['2013-09-12'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['acme_5']},

#
# acme_6
#
# By superelchi, thx pepe
# 2013-09-13
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[187369777, 2842286875, 2, 2]], 'Credit': ['By superelchi, thx pepe'], 'Lcd_height': '128', 'Date': ['2013-09-13'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['acme_6']},

#
# agk_violet
#
#
{'Status': 'supported', 'ContrastSupport': 'No', 'CRC': [[3589264857, 1422689575]], 'Lcd_height': '128', 'Lcd_width': '128', 'ContrastMenuSupport': 'No', 'Type': ['agk_violet']},

#
# august_dp150a
#
# By superelchi
# 2013-02-12
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[640222753, 3948976512, 1, 1]], 'Url': ['http://www.amazon.de/dp/B001N96F3I/ref=pe_217221_31005211_dp_1'], 'Credit': ['By superelchi'], 'Lcd_height': '128', 'Date': ['2013-02-12'], 'Lcd_width': '128', 'ContrastMenuSupport': 'No', 'Type': ['august_dp150a']},

#
# avlabs_avl969s
#
# By ax206geek
# 2012-06-17
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[741602581, 838517843]], 'Url': ['http://www.avlabs.net'], 'Credit': ['By ax206geek'], 'Lcd_height': '128', 'Date': ['2012-06-17'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['avlabs_avl969s']},

#
# carrefour_bfv151
#
# By superelchi, thx assas1
# 2012-11-02
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[3189525217, 3498632343]], 'Url': ['http://www.mjshk.com/products/Digital%20Photo%20Frame/page/DPF815A_Max.htm', 'http://www.prixing.fr/products/bfv151-1-5-pouce-cadre-photo-porte-cles-carrefour-3606605023771'], 'Credit': ['By superelchi, thx assas1'], 'Lcd_height': '128', 'Date': ['2012-11-02'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['carrefour_bfv151']},

#
# clas_ohlson
#
# By superelchi, thx BufferFramed
# 2012-12-05
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[640222753, 4127089957]], 'Url': ['http://www.clasohlson.com/fi/Avaimenper%C3%A4,-jossa-digitaalinen-valokuvakehys/Pr383925000'], 'Credit': ['By superelchi, thx BufferFramed'], 'Lcd_height': '128', 'Date': ['2012-12-05'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['clas_ohlson']},

#
# clas_ohlson_2
#
# By superelchi, thx josef
# 2013-10-01
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[2834891419, 2508033262, 1, 1]], 'Credit': ['By superelchi, thx josef'], 'Lcd_height': '128', 'Date': ['2013-10-01'], 'Lcd_width': '128', 'ContrastMenuSupport': 'No', 'Type': ['clas_ohlson_2']},

#
# coby_dp151_bw
#
# By superelchi, thx mrlinux
# 2012-07-24
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[287174071, 805928632]], 'Url': ['http://www.ebay.com/itm/280828187564'], 'Credit': ['By superelchi, thx mrlinux'], 'Lcd_height': '128', 'Date': ['2012-07-24'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['coby_dp151_bw']},

#
# coby_dp151_bw_2
#
# By superelchi, thx Deamon666
# 2013-08-18
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[3589761504, 3573247145, 2, 2]], 'Credit': ['By superelchi, thx Deamon666'], 'Lcd_height': '128', 'Date': ['2013-08-18'], 'Lcd_width': '128', 'ContrastMenuSupport': 'No', 'Type': ['coby_dp151_bw_2']},

#
# coby_dp151_white
#
# By superelchi, thx donashe
# 2012-05-14
#
{'Status': 'supported', 'ContrastSupport': 'No', 'CRC': [[3562395993, 464803725]], 'Url': ['http://www.frys.com/product/5439059'], 'Credit': ['By superelchi, thx donashe'], 'Lcd_height': '128', 'Date': ['2012-05-14'], 'Lcd_width': '128', 'ContrastMenuSupport': 'No', 'Type': ['coby_dp151_white']},

#
# delightdigi_3
#
# By superelchi, thx fling
# 2013-06-18
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[3589264857, 3321933551, 1, 1]], 'Credit': ['By superelchi, thx fling'], 'Lcd_height': '128', 'Date': ['2013-06-18'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['delightdigi_3']},

#
# delightdigi_black
#
# From ebay seller delight-digi
# By superelchi, thx rotitude
# 2012-04-22
#
{'Comment': ['From ebay seller delight-digi'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'Credit': ['By superelchi, thx rotitude'], 'CRC': [[3718890135, 3664700611]], 'Lcd_height': '128', 'Date': ['2012-04-22'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['delightdigi_black']},

#
# dx27893
#
# Works with dx #27893 (white) & #27894 (blue)
# By superelchi
# 2012-07-28
#
{'Comment': ['Works with dx #27893 (white) & #27894 (blue)'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[3589264857, 1297118871, 1, 1], [3589264857, 2760090716, 1, 1]], 'Url': ['http://www.dealextreme.com/p/1-5-lcd-rechargeable-digital-usb-photo-frame-keychain-white-107-picture-memory-storage-27893', 'http://www.dealextreme.com/p/1-5-lcd-rechargeable-digital-usb-photo-frame-keychain-blue-107-picture-memory-storage-27894', 'http://dx.com/p/1-5-lcd-rechargeable-digital-usb-photo-frame-keychain-with-8m-memory-for-140-photos-silver-33624', 'http://www.amazon.de/Technaxx-Keypix-Digitaler-Fotorahmen-interner/dp/B0013SJV4O', 'http://www.7dayshop.com/7dayshop-pebble-digital-photo-frame-1-5-tft-keyring-version-silver-irresistible-price'], 'Credit': ['By superelchi'], 'Lcd_height': '128', 'Date': ['2012-07-28'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['dx27893']},

#
# dx27893_2
#
# Variation of dx27893
# By superelchi, thx RedoX
# 2012-07-24
#
{'Comment': ['Variation of dx27893'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[1743538178, 2452384647]], 'Url': ['http://www.dealextreme.com/p/1-5-lcd-rechargeable-digital-usb-photo-frame-keychain-white-107-picture-memory-storage-27893'], 'Credit': ['By superelchi, thx RedoX'], 'Lcd_height': '128', 'Date': ['2012-07-24'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['dx27893_2']},

#
# eachdesk_tumbler
#
# Nice enclosure: tumbler design.
# By superelchi (thx c.dent)
# 2012-07-28
#
{'Comment': ['Nice enclosure: tumbler design.'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[3589264857, 1730849026]], 'Url': ['http://www.ebay.com/itm/Hot-1-5-Digital-Photo-Frame-Picture-Album-16MB-New-Tumbler-03-/110842497224'], 'Credit': ['By superelchi (thx c.dent)'], 'Lcd_height': '128', 'Date': ['2012-07-28'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['eachdesk_tumbler']},

#
# estation100
#
# By superelchi, thx galvan
# 2013-06-19
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[1797375145, 652807694, 1, 1]], 'Url': ['http://www.ebay.com/itm/380532649879'], 'Credit': ['By superelchi, thx galvan'], 'Lcd_height': '128', 'Date': ['2013-06-19'], 'Lcd_width': '128', 'ContrastMenuSupport': 'No', 'Type': ['estation100']},

#
# intertronic
#
# By superelchi, thx grouproot
# 2012-10-22
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[3718890135, 1505088704]], 'Url': ['http://www.interdiscount.ch/idshop/product/Spielwaren/873152_ER-324609050132160/INTERTRONIC_Digitaler_Bilderrahmen/detail.jsf'], 'Credit': ['By superelchi, thx grouproot'], 'Lcd_height': '128', 'Date': ['2012-10-22'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['intertronic']},

#
# jovisa
#
# By superelchi, thx djJack
# 2012-09-19
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[2726181921, 2701100526]], 'Url': ['http://www.jovisa.biz/images/egg%20dpf%20or%20copy.jpg'], 'Credit': ['By superelchi, thx djJack'], 'Lcd_height': '128', 'Date': ['2012-09-19'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['jovisa']},

#
# kaiser_baas_n1879
#
# From OfficeWorks (Perth Australia)
# By superelchi, thx John
# 2013-07-21
#
{'Comment': ['From OfficeWorks (Perth Australia) '], 'Status': 'supported', 'ContrastSupport': 'Yes', 'Credit': ['By superelchi, thx John'], 'CRC': [[3589264857, 4097396536, 1, 1]], 'Lcd_height': '128', 'Date': ['2013-07-21'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['kaiser_baas_n1879']},

#
# neckermann
#
# Gift from german seller neckermann.de (no longer available.)
# By superelchi, thx Anaeijon
# 2013-06-27
#
{'Comment': ['Gift from german seller neckermann.de (no longer available.)'], 'Status': 'supported', 'ContrastSupport': 'No', 'Credit': ['By superelchi, thx Anaeijon '], 'CRC': [[1825083451, 856513154, 2, 0]], 'Lcd_height': '128', 'Date': ['2013-06-27'], 'Lcd_width': '128', 'ContrastMenuSupport': 'No', 'Type': ['neckermann']},

#
# sevendayshop_pebble
#
# By superelchi, thx daveg
# 2012-10-19
#
{'Status': 'supported', 'ContrastSupport': 'No', 'CRC': [[1493111108, 2479827774]], 'Url': ['http://www.7dayshop.com/7dayshop-pebble-digital-photo-frame-1-5-tft-keyring-version-silver-irresistible-price'], 'Credit': ['By superelchi, thx daveg'], 'Lcd_height': '128', 'Date': ['2012-10-19'], 'Lcd_width': '128', 'ContrastMenuSupport': 'No', 'Type': ['sevendayshop_pebble']},

#
# sunluxy
#
# By superelchi, thx glb
# 2013-01-27
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[2726181921, 3709981863]], 'Url': ['http://www.amazon.fr/gp/product/B00AQV277C/'], 'Credit': ['By superelchi, thx glb'], 'Lcd_height': '128', 'Date': ['2013-01-27'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['sunluxy']},

#
# tao_80013
#
# By superelchi, thx richard
# 2013-07-21
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[640222753, 4280902475, 2, 2]], 'Url': ['http://cpc.farnell.com/jsp/search/productdetail.jsp?sku=CS1967434'], 'Credit': ['By superelchi, thx richard'], 'Lcd_height': '128', 'Date': ['2013-07-21'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['tao_80013']},

#
# veovision
#
# By superelchi, thx ternyk
# 2013-02-13
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[3589264857, 3308761215]], 'Credit': ['By superelchi, thx ternyk'], 'Lcd_height': '128', 'Date': ['2013-02-13'], 'Lcd_width': '128', 'ContrastMenuSupport': 'No', 'Type': ['veovision']},

#
# xg4241
#
# Does not use standard LcdInit. Direct lcd access (NOT using otp_lcd_write).
# By superelchi (thx marcusbrutus)
# 2013-03-17
#
{'Comment': ['Does not use standard LcdInit. Direct lcd access (NOT using otp_lcd_write).'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[2280663442, 4014062118, 2, 2]], 'Url': ['http://dicksmith.com.au/product/XG4241/dick-smith-1-5-quot-digital-photo-frame-keyring'], 'Credit': ['By superelchi (thx marcusbrutus)'], 'Lcd_height': '128', 'Date': ['2013-03-17'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['xg4241']},

#
# zipp_dp605
#
# Sold in Australia by Big W / Woolworths.
# By superelchi (thx CaptainCheeks)
# 2013-03-05
#
{'Comment': ['Sold in Australia by Big W / Woolworths.'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'Credit': ['By superelchi (thx CaptainCheeks)'], 'CRC': [[3589761504, 605483227, 2, 2]], 'Lcd_height': '128', 'Date': ['2013-03-05'], 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['zipp_dp605']},

###################### 128 x 144 ##############################

#
# focalprice144
#
# By superelchi
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[811528212, 1201222071]], 'Credit': ['By superelchi'], 'Lcd_height': '144', 'Lcd_width': '128', 'ContrastMenuSupport': 'Yes', 'Type': ['focalprice144']},

###################### 160 x 128 ##############################

#
# coby_dp180
#
# By superelchi (thx johni)
# 2013-03-02
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[553029627, 623803278, 2, 2]], 'Url': ['http://www.cobyusa.com/?p=prod&prod_num_id=411&pcat_id=4001'], 'Credit': ['By superelchi (thx johni)'], 'Lcd_height': '128', 'Date': ['2013-03-02'], 'Lcd_width': '160', 'ContrastMenuSupport': 'Yes', 'Type': ['coby_dp180']},

###################### 240 x 320 ##############################

#
# delightdigi_2_portrait
#
# Portrait mode, different enclosure, battery powered
# By superelchi, thx dms
# 2012-09-28
#
{'Comment': ['Portrait mode, different enclosure, battery powered'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[472729229, 1980929741, 1, 1]], 'Url': ['http://www.ebay.com/itm/280736717264'], 'Credit': ['By superelchi, thx dms'], 'Lcd_height': '320', 'Date': ['2012-09-28'], 'Lcd_width': '240', 'ContrastMenuSupport': 'No', 'Type': ['delightdigi_2_portrait']},

#
# linkdelight_black_portrait
#
# Portrait mode, different enclosure, battery powered
# By superelchi, thx Papa Oscar
# 2013-01-18
#
{'Comment': ['Portrait mode, different enclosure, battery powered'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[3230522243, 2026185173, 1, 1]], 'Url': [' http://www.ebay.com/itm/230670117410'], 'Credit': ['By superelchi, thx Papa Oscar'], 'Lcd_height': '320', 'Date': ['2013-01-18'], 'Lcd_width': '240', 'ContrastMenuSupport': 'No', 'Type': ['linkdelight_black_portrait']},

#
# linkdelight_black_portrait_2
#
# Variation of linkdelight_black_portrait
# By superelchi (thx Mr. P)
# 2013-03-27
#
{'Comment': ['Variation of linkdelight_black_portrait'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'Credit': ['By superelchi (thx Mr. P)'], 'CRC': [[1040606659, 902033657, 1, 1]], 'Lcd_height': '320', 'Date': ['2013-03-27'], 'Lcd_width': '240', 'ContrastMenuSupport': 'No', 'Type': ['linkdelight_black_portrait_2']},

#
# linkdelight_black_portrait_3
#
# Another variation of linkdelight_black_portrait
# By superelchi, thx prezes551
# 2013-05-09
#
{'Comment': ['Another variation of linkdelight_black_portrait'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[1040606659, 2896831531, 1, 1]], 'Url': ['http://www.ebay.com/itm/230670117410'], 'Credit': ['By superelchi, thx prezes551'], 'Lcd_height': '320', 'Date': ['2013-05-09'], 'Lcd_width': '240', 'ContrastMenuSupport': 'No', 'Type': ['linkdelight_black_portrait_3']},

#
# yallstock_black_portrait
#
# By superelchi (thx dkrusko)
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[4077944897, 334688753, 1, 1]], 'Url': ['http://www.ebay.com/itm/400391394538'], 'Credit': ['By superelchi (thx dkrusko)'], 'Lcd_height': '320', 'Lcd_width': '240', 'ContrastMenuSupport': 'No', 'Type': ['yallstock_black_portrait']},

###################### 320 x 240 ##############################

#
# acme_4
#
# unknown ebay seller.
# By superelchi, thx nexus
# 2013-09-05
#
{'Comment': ['unknown ebay seller.'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'Credit': ['By superelchi, thx nexus'], 'CRC': [[817616278, 404446180, 1, 1]], 'Lcd_height': '240', 'Date': ['2013-09-05'], 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['acme_4']},

#
# dhgate
#
# 50 pieces/lot
# By superelchi, thx Rollkopf
# 2013-08-16
#
{'Comment': ['50 pieces/lot'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[1317613437, 855243777, 1, 1]], 'Url': ['http://www.dhgate.com/product/2-4-inch-multifunctional-lcd-digital-photo/143997976.html'], 'Credit': ['By superelchi, thx Rollkopf'], 'Lcd_height': '240', 'Date': ['2013-08-16'], 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['dhgate']},

#
# dinodirect
#
# By superelchi, thx kodi
# 2013-05-31
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[390860985, 2045744741, 2, 1]], 'Url': ['http://www.dinodirect.com/2-4-LCD-16MB-Digital-Photo-Frame-White.html'], 'Credit': ['By superelchi, thx kodi'], 'Lcd_height': '240', 'Date': ['2013-05-31'], 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['dinodirect']},

#
# dx104500
#
# By superelchi
#
{'Status': 'supported', 'ContrastSupport': 'No', 'CRC': [[3029278881, 3683529480, 2, 0]], 'Url': ['http://www.dealextreme.com/p/stylish-a33-2-4-lcd-desktop-digital-photo-picture-frame-album-silver-16mb-104500'], 'Credit': ['By superelchi'], 'Lcd_height': '240', 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['dx104500']},

#
# dx104838
#
# No Brightness control. Only on/off supported.
# By superelchi
#
{'Comment': ['No Brightness control. Only on/off supported.'], 'Status': 'supported', 'ContrastSupport': 'No', 'Credit': ['By superelchi'], 'Url': ['http://www.dealextreme.com/p/stylish-a18-2-4-lcd-desktop-digital-photo-picture-frame-album-white-silver-16mb-104838'], 'CRC': [[3790308462, 2319538268, 0, 0]], 'Lcd_height': '240', 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['dx104838']},

#
# dx104838_2
#
# No Brightness control. Only on/off supported.
# By superelchi (thx j3r, mihre)
#
{'Comment': ['No Brightness control. Only on/off supported.'], 'Status': 'supported', 'ContrastSupport': 'No', 'Credit': ['By superelchi (thx j3r, mihre)'], 'Url': ['http://www.dealextreme.com/p/stylish-a18-2-4-lcd-desktop-digital-photo-picture-frame-album-white-silver-16mb-104838'], 'CRC': [[3029278881, 3683529480, 0, 0]], 'Lcd_height': '240', 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['dx104838_2']},

#
# dx104838_3
#
# No Brightness control. Only on/off supported.
# By superelchi (thx ralf001)
#
{'Comment': ['No Brightness control. Only on/off supported.'], 'Status': 'supported', 'ContrastSupport': 'No', 'Credit': ['By superelchi (thx ralf001)'], 'Url': ['http://www.dealextreme.com/p/stylish-a18-2-4-lcd-desktop-digital-photo-picture-frame-album-white-silver-16mb-104838'], 'CRC': [[3790308462, 4249249994, 0, 0]], 'Lcd_height': '240', 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['dx104838_3']},

#
# dx21334a
#
# By superelchi
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[3887821308, 1405237147, 1, 1]], 'Url': ['http://www.dealextreme.com/p/2-4-lcd-desktop-digital-photo-frame-and-calendar-27-picture-memory-storage-21334'], 'Credit': ['By superelchi'], 'Lcd_height': '240', 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['dx21334a']},

#
# dx21334b
#
# By superelchi
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[4101150613, 3339371474]], 'Url': ['http://www.dealextreme.com/p/2-4-lcd-desktop-digital-photo-frame-and-calendar-27-picture-memory-storage-21334', 'http://www.ebay.de/itm/160792780280'], 'Credit': ['By superelchi'], 'Lcd_height': '240', 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['dx21334b']},

#
# focal_custom
#
# Replaces deprecated type focal
# By superelchi, thx mihre
# 2013-05-13
#
{'Comment': ['Replaces deprecated type focal'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'Credit': ['By superelchi, thx mihre'], 'CRC': [[390860985, 4226618260, 2, 1]], 'Lcd_height': '240', 'Date': ['2013-05-13'], 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['focal_custom']},

#
# focal_custom_2
#
# Replaces deprecated type focal
# By superelchi
# 2013-05-13
#
{'Comment': ['Replaces deprecated type focal'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'Credit': ['By superelchi'], 'CRC': [[390860985, 2754887347, 1, 1]], 'Lcd_height': '240', 'Date': ['2013-05-13'], 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['focal_custom_2']},

#
# linkdelight
#
# By superelchi
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[860617845, 806655299, 1, 1]], 'Url': ['http://www.ebay.de/itm/ws/eBayISAPI.dll?ViewItem&rd=1&item=260978964426&ssPageName=STRK:MEAFB:IT', 'http://www.ebay.de/itm/New-Mini-2-4-inch-Digital-Time-Day-Calendar-Alarm-Clock-Photo-Frame-POF16-/260883908884?pt=LH_DefaultDomain_0&hash=item3cbde48914#ht_4709wt_1046'], 'Credit': ['By superelchi'], 'Lcd_height': '240', 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['linkdelight']},

#
# linkdelight_2
#
# Variation of linkdelight
# By superelchi, thx fred_feuerstein
# 2012-09-07
#
{'Comment': ['Variation of linkdelight'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[841589230, 1030004459, 1, 1]], 'Url': ['http://www.ebay.de/itm/ws/eBayISAPI.dll?ViewItem&rd=1&item=260883908884'], 'Credit': ['By superelchi, thx fred_feuerstein'], 'Lcd_height': '240', 'Date': ['2012-09-07'], 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['linkdelight_2']},

#
# linkdelight_3
#
# Variation of linkdelight
# By superelchi, thx ax206geek, m_K_o
# 2012-10-16
#
{'Comment': ['Variation of linkdelight'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[3935538804, 3754832255]], 'Url': ['http://www.ebay.de/itm/260978964426?ssPageName=STRK:MEWNX:IT&_trksid=p3984.m1439.l2649'], 'Credit': ['By superelchi, thx ax206geek, m_K_o'], 'Lcd_height': '240', 'Date': ['2012-10-16'], 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['linkdelight_3']},

#
# linkdelight_4
#
# Another variation of linkdelight
# By superelchi, thx Solo0815
# 2012-12-01
#
{'Comment': ['Another variation of linkdelight'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[1722727966, 3339371474]], 'Url': ['http://www.ebay.de/itm/260978964426?ssPageName=STRK:MEWNX:IT&_trksid=p3984.m1497.l2649'], 'Credit': ['By superelchi, thx Solo0815'], 'Lcd_height': '240', 'Date': ['2012-12-01'], 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['linkdelight_4']},

#
# linkdelight_5
#
# Another variation of linkdelight
# By superelchi
#
{'Comment': ['Another variation of linkdelight'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'Credit': ['By superelchi'], 'Url': ['http://www.ebay.de/itm/ws/eBayISAPI.dll?ViewItem&item=110897096126'], 'CRC': [[2108676850, 2938400978]], 'Lcd_height': '240', 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['linkdelight_5']},

#
# newfrog
#
# No Brightness control. Only on/off supported.
# By superelchi, thx LUISE
# 2013-06-24
#
{'Comment': ['No Brightness control. Only on/off supported.'], 'Status': 'supported', 'ContrastSupport': 'No', 'CRC': [[2532357239, 2963443671, 0, 0]], 'Url': ['http://www.newfrog.com/p/2-4-inch-usb-digital-time-day-calendar-alarm-clock-photo-frame-viewer-pof16-new-25642.html'], 'Credit': ['By superelchi, thx LUISE'], 'Lcd_height': '240', 'Date': ['2013-06-24'], 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['newfrog']},

#
# pearl_custom
#
# Custom (flash-dump based) version of pearl
# By superelchi
# 2012-07-28
#
{'Comment': ['Custom (flash-dump based) version of pearl'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[497821697, 3130612463, 2, 1]], 'Url': ['http://www.pearl.de/a-HPM1184-5618.shtml'], 'Credit': ['By superelchi'], 'Lcd_height': '240', 'Date': ['2012-07-28'], 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['pearl_custom']},

#
# pt824
#
# Should work with PT824A/B/C.
# By superelchi (thx olderzeus)
# 2012-11-24
#
{'Comment': ['Should work with PT824A/B/C.'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[497821697, 3923636230]], 'Url': ['http://item.taobao.com/item.htm?id=9197767508', 'http://www.longmatech.com/index.php/product/PT824A.html', 'http://www.longmatech.com/index.php/product/PT824A.html', 'http://lucy89.en.made-in-china.com/product/RbUxXeCrhvcJ/China-Christmas-Gifts-Digital-Photo-Frame-PT824b.html', 'http://konsun.appliances-china.com/Product_Look.php?ID=100077', 'http://www.corpmarket.com/sell/2-4inch-digital-photo-frame-PT824C-detail-1245-747967.html', 'http://www.gongchang.com/2_4_inch_color_LCD_display_PT824C_digital_picture_viewer_heart_shaped-dp621446/'], 'Credit': ['By superelchi (thx olderzeus)'], 'Lcd_height': '240', 'Date': ['2012-11-24'], 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['pt824']},

#
# taobao
#
# Also used by linkdelight.
# By superelchi (thx cuckoohello)
# 2013-01-05
#
{'Comment': ['Also used by linkdelight.'], 'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[2212265512, 1765720342]], 'Url': ['http://item.taobao.com/item.htm?id=10380777914'], 'Credit': ['By superelchi (thx cuckoohello)'], 'Lcd_height': '240', 'Date': ['2013-01-05'], 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['taobao']},

#
# taobao_2
#
# By superelchi, thx elickson
# 2013-09-24
#
{'Status': 'supported', 'ContrastSupport': 'Yes', 'CRC': [[1722727966, 3336180541, 1, 1]], 'Url': ['http://item.taobao.com/item.htm?id=5827115943'], 'Credit': ['By superelchi, thx elickson'], 'Lcd_height': '240', 'Date': ['2013-09-24'], 'Lcd_width': '320', 'ContrastMenuSupport': 'No', 'Type': ['taobao_2']},

]
