/**************************************************************************
 * 
 *
 * This file was generated by dclib/netpp. Modifications to this file will
 * be lost.
 * Stylesheet: reg8051.xsl       (c) 2010-2011 section5
 *
 * Version: 0.0develop
 **************************************************************************/



#ifndef _BITMASK_
#define _BITMASK_(msb, lsb) ( (-1 << (msb + 1)) ^ (-1 << lsb) )
#endif
#ifndef _BIT_
#define _BIT_(pos) (1 << pos)
#endif



/*********************************************************
 * Address segment 'LCD'
 *********************************************************/
		
#define R_LCD_Nop                  0x00
#define R_LCD_Reset                0x01
#define R_LCD_Id                   0x04
#define R_LCD_Status               0x09
#define R_LCD_PowerMode            0x0a
#define R_LCD_ReadMADCTL           0x0b
#define R_LCD_ReadPixFormat        0x0c
#define R_LCD_ReadImgMode          0x0d
#define R_LCD_ReadSignalMode       0x0e
#define R_LCD_ReadSignalMode2      0x0f
#define R_LCD_SleepIn              0x10
#define R_LCD_SleepOut             0x11
#define R_LCD_PartialMode          0x12
#define R_LCD_NormalDispMode       0x13
#define R_LCD_DispInversionOff     0x20
#define R_LCD_DispInversionOn      0x21
#define R_LCD_GammaSet             0x26
#define R_LCD_DisplayOff           0x28
#define R_LCD_DisplayOn            0x29
#define R_LCD_ColumnAddress        0x2a
#define R_LCD_PageAddress          0x2b
#define R_LCD_MemoryWrite          0x2c
#define R_LCD_ColorSetting         0x2d
#define R_LCD_MemoryRead           0x2e
#define R_LCD_PartialArea          0x30
#define R_LCD_VScrollDef           0x33
#define R_LCD_TearingEffectLineOff 0x34
#define R_LCD_TearingEffectLineOn  0x35
#define R_LCD_MemoryAccessControl  0x36
#define R_LCD_VScrollStartAddr     0x37
#define R_LCD_IdleOff              0x38
#define R_LCD_IdleOn               0x39
#define R_LCD_InterfacePixelFormat 0x3a
#define R_LCD_ReadId1              0xda
#define R_LCD_ReadId2              0xdb
#define R_LCD_ReadId3              0xdc
#define R_LCD_FrameRateControl1    0xb1
#define R_LCD_FrameRateControl2    0xb2
#define R_LCD_FrameRateControl3    0xb3
#define R_LCD_DisplayInversion     0xb4
#define R_LCD_RGBPorchSetting      0xb5
#define R_LCD_DispFuncSet          0xb6
#define R_LCD_SourceDriverControl  0xb7
#define R_LCD_GateDriverControl    0xb8
#define R_LCD_PowerControl1        0xc0
#define R_LCD_PowerControl2        0xc1
#define R_LCD_PowerControl3        0xc2
#define R_LCD_PowerControl4        0xc3
#define R_LCD_PowerControl5        0xc4
#define R_LCD_VComControl1         0xc5
#define R_LCD_VComControl2         0xc6
#define R_LCD_VComOffsetControl    0xc7
#define R_LCD_WriteId4Value        0xd3
#define R_LCD_NVMemFuncControl     0xd7
#define R_LCD_NVMemFuncControl2    0xde
#define R_LCD_PosGammaCorrection   0xe0
#define R_LCD_NegGammaCorrection   0xe1
#define R_LCD_GamRSel              0xf2
